### ISSUE TITLE
Image Corruption at top of Screen and Rolling Image with forced_scandoubler=1

### ISSUE THREAD

**Issue by 630216-29-2400** [MiSTer-devel/Arcade-Raizing_MiSTer#32] opened 2022-08-20 18:33 UTC
Don't use gighub so please excuse any errors in my report.

I have no way to test analogue output but irrelevant of the resolutions that I try I'm having graphical issues with all variations of Armed Police Batrider, Battle Bakraid, Battle Garegga, Kingdom Grandprix and Sorcer Striker.
The top maybe 5% of the image is distorted, it's always been that way but since the latest update in now shows corrupt letter that says High Score so maybe releated to that in the recent update.
The incorrect high score stuff at the top is absolutely identical irrelevant of the game or settings that are used, even after a hard reset of the system.
![IMG_4382](https://user-images.githubusercontent.com/25779045/185761329-48b383c9-76dc-4bef-82b4-2b5d16140827.jpg)
Also, the whole of the game screen constantly ripples up and down a few pixels. It's the same with all the games and output resolutions (HDMI).
Again, this rolling has been there since the initial release so isn't new. Why haven't I reported it before? I dont use this place and it is a core still in development and I assumed that it was just something that would be known and would be sorted at some point as things went on. Also, I didn't want to sound like I was moaning in some way about such a fantastic core andI suppose it could also be connected to the other open issue.

**Comment by psomashekar** [comment] 2022-08-21 05:16
It's possible that it's something in your setup, because I haven't seen this issue reported. Also, I checked just now, and it looks like this for me:
![1661058910049263413070908304429](https://user-images.githubusercontent.com/976353/185776604-dbb632ac-e863-4f41-b91b-af1b0f3ca306.jpg)

So the top of the image looks fine.

**Comment by 630216-29-2400** [comment] 2022-08-21 18:13
Thanks, I had been wondering why I'd not seen anything of this issue anywhere else, your replay made me go back and test a few other settings.
Some time back it was recommended to me to activate the forced_scandoubler option in the ini due to the obvious benefits of doubling the resolution on a single axis. Testing these cores without the forced scandoubling does fix the issue in these cores.
I'm not actually sure if the benefits of forced scandoubling even apply now due to being able to output at higher resolutions now. Strangely though, it is only an issue with these specific cores and I've briefly tested several other arcade cores that I'd not used for ages and everything else still seems fine with it.
I will leave this open and of course it can be closed if it's seen as a non issue, I'm not really sure how relevant the setting is these days with the increased resolution.
Thanks, either way.

**Comment by psomashekar** [comment] 2022-08-21 21:41
Thanks for the update. @atrac17 wondering if you know anything about this setting?

**Comment by cesetxeberria** [comment] 2022-08-23 18:51
I can confirm this issue. I have my mister connected to a 31khz pc crt, using forced_scandoubler=1.
According to my monitor info, resolution is constantly changing between 480x321 and 480x322

**Comment by psomashekar** [comment] 2022-08-30 23:01
Fixed in latest build.

**Closed** 2022-08-30 23:01 UTC

**Comment by 630216-29-2400** [comment] 2022-09-01 16:47
The previous update did fix it but it has returned after updating today to these core versions:
- Bakraid_20220830
- Batrider_20220830
- Garegga_20220830

**Comment by psomashekar** [comment] 2022-09-06 12:23
bakraid is in a state of flux. I reverted back to a previous version for another issue going on

**Comment by 630216-29-2400** [comment] 2022-09-06 12:37
Thanks,
Never quite sure when I should respond with this stuff as I know I know things are still being worked on.
