### ISSUE TITLE
Sprite Lag Issue

### ISSUE THREAD

**Issue by rogalian** [MiSTer-devel/Arcade-Raizing_MiSTer#20] opened 2022-08-07 11:35 UTC
There appears to be a problem with certain graphical elements not sticking together properly. It's particularly noticeable on the first boss, where moving left and right causes the fuselage and engines to detach from the wings (using Silver Sword).

I've attached a video that shows the problem.

https://user-images.githubusercontent.com/5140184/183288485-85a93af9-d5b7-41fe-b341-be081b6578e2.mp4

**Comment by rogalian** [comment] 2022-08-07 11:49
Here is how it should look - captured from an original PCB.
Uploading IMG_4166.mp4…

**Comment by psomashekar** [comment] 2022-08-07 18:47
Yea, I don't see this, though I am running on hdmi. I think another person reported something similar, and it may be caused by the clocks and timing. We are taking a look at the overall clocks and timing anyway, so I think this issue should be fixed when we fix that.

**Comment by Optiroc** [comment] 2022-08-08 12:04
I also noticed this within seconds. It’s easy to observe by moving sideways and looking at ground enemies like turrets or tanks – they don’t move in sync with the background layer. 

I believe the board uses a sprite framebuffer, and if that isn’t implemented correctly the background will lag behind by a frame or two. (Just a hunch!)

**Comment by psomashekar** [comment] 2022-08-08 14:21
> I also noticed this within seconds. It’s easy to observe by moving sideways and looking at ground enemies like turrets or tanks – they don’t move in sync with the background layer. 
> 
> I believe the board uses a sprite framebuffer, and if that isn’t implemented correctly the background will lag behind by a frame or two. (Just a hunch!)

No, that's not how the games work. There's no extra framebuffer for sprites, and all 3 games use the same gp9001 config. The only thing is in batrider there's double buffered sprites, but that's basically the sprite queue mirrored.

**Comment by Optiroc** [comment] 2022-08-08 14:59
Right. Are you sure that Garegga doesn’t also use the double buffered sprite queue? Not doing it would likely manifest in the same type of misalignment, I would guess.

**Comment by psomashekar** [comment] 2022-08-08 15:32
> Right. Are you sure that Garegga doesn’t also use the double buffered sprite queue? Not doing it would likely manifest in the same type of misalignment, I would guess. 

No, Garegga doesn't have any double buffering.

Actually if I had to guess, this is most likely related to another issue I am researching regarding calculation of the Sprite scroll y offsets. Garegga also uses a different value for that than other games.

**Comment by atrac17** [comment] 2022-08-08 15:34
> > Right. Are you sure that Garegga doesn’t also use the double buffered sprite queue? Not doing it would likely manifest in the same type of misalignment, I would guess.
> 
> No, Garegga doesn't have any double buffering.
> 
> Actually if I had to guess, this is most likely related to another issue I am researching regarding calculation of the Sprite scroll y offsets. Garegga also uses a different value for that than other games.

I backup this assessment. Left a note elsewhere for you too.

**Comment by psomashekar** [comment] 2022-08-08 15:41
Sprite ram is mirrored in batrider and bakraid, that's about all. Garegga and below all direct access and single.

**Comment by eturquin** [comment] 2022-08-09 22:29
I have noticed this issue as well, especially in Garegga (playing on a HDMI TV, 1080p 60hz), where many elements (explosion impacts on the ground, after an enemy has been destroyed, are a good example) seem to react to lateral scrolling with a delay, which gives the impression that they detached from the background and floating above.

**Comment by psomashekar** [comment] 2022-08-12 13:38
I found the source of this issue. Garegga has 2 frames of sprite lag. So, whatever sprites are drawn are actually based on the contents of sprite ram 2 frames ago. In a double buffering scenario, it would be based on one frame ago. I was able to also replicate this issue in final burn neo, so garegga exhibits the same issue there as well.

**Comment by psomashekar** [comment] 2022-08-14 05:12
The fix I implemented tonight seems to work well. I am testing the other games as well. Will generate a new build with the latest changes if all is well.

**Comment by psomashekar** [comment] 2022-08-14 06:53
the lag is only 1 frame in bakraid and batrider from my testing. new build will be published with fix.

**Closed by psomashekar** 2022-08-14 06:53 UTC
Labels: bug

**Comment by psomashekar** [comment] 2022-08-14 07:00
New build published with fix.
